rating <- 1:4
animal <- c('koala', 'hedgehog', 'sloth', 'panda')
country <- c('Australia', 'Italy', 'Peru', 'China')
avg_sleep_hours <- c(21, 18, 17, 10)
super_sleepers <- data.frame(rating, animal, country, avg_sleep_hours)
print(super_sleepers)
print(super_sleepers$country)
print(super_sleepers[1:2,])
max_lifespan<-c(18,5,30,20)
bears<-cbind(super_sleepers,max_lifespan)
print(bears)
s5<-c(5,'polar bear','norway',8,30)
bears1<-rbind(bears,s5)
print(bears1)